version: '3.8'

services:
  app:
    build: .
    container_name: nkr_app
    ports:
      - "3400:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=rawinda_secret
      - DB_NAME=rawinda_finance
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: nkr_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rawinda_secret
      - POSTGRES_DB=rawinda_finance
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
